import type { Metadata } from "next";
import { ApiProviders } from "@/shared/api/providers";
import { TopBar } from "@/shared/ui/top-bar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="ko" data-theme="light">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/variable/pretendardvariable-dynamic-subset.min.css" />
      </head>
      <body className="bg-[var(--bg-base)] text-[var(--text-primary)] min-h-full flex flex-col">
        <TopBar />
        <ApiProviders>{children}</ApiProviders>
      </body>
    </html>
  );
}
