"""region_industry_metric open close nullable

Revision ID: e2a08b1e8f19
Revises: 8236d5263b60
Create Date: 2026-09-17 10:47:49.947538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a08b1e8f19'
down_revision: Union[str, Sequence[str], None] = '8236d5263b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('region_industry_metric', 'open_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('region_industry_metric', 'close_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('region_industry_metric', 'close_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('region_industry_metric', 'open_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
